name: Genereate data
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - name: Set up environment
      run: |
        bundle install --without default jekyll_plugins
    - name: Run parser
      run: ruby parser.rb untappd.json
    - name: Commit back
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        git add -A .
        git commit -m "Genereated new data"
        git push
